# Generated by Django 3.2.6 on 2021-08-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210806_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('P1', '1 ответ'), ('P2', '1/много ответов'), ('REL', 'Соотнести'), ('MANY', 'Пункты'), ('STR', 'Текст')], default='STR', max_length=4),
        ),
        migrations.AlterField(
            model_name='varlist',
            name='is_right',
            field=models.BooleanField(default=True, verbose_name='Правильность'),
        ),
    ]
