# Generated by Django 3.2.6 on 2021-08-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Иллюстрация к вопросу'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Иллюстрация к вопросу'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Иллюстрация к вопросу'),
        ),
        migrations.AlterField(
            model_name='question',
            name='imageA1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Иллюстрация к ответу'),
        ),
        migrations.AlterField(
            model_name='question',
            name='imageA2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Иллюстрация к ответу'),
        ),
        migrations.AlterField(
            model_name='question',
            name='imageA3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Иллюстрация к ответу'),
        ),
    ]
