# Generated by Django 3.2.6 on 2021-08-06 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210806_0322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relinitials',
            options={'ordering': ['parent_question'], 'verbose_name': 'RelInitials', 'verbose_name_plural': 'RelInitial'},
        ),
        migrations.AlterModelOptions(
            name='varlist',
            options={'ordering': ['parent_question'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
    ]
