# Generated by Django 3.2.6 on 2021-08-06 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_relinitials_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelInitials',
            new_name='RelInitial',
        ),
        migrations.AlterModelOptions(
            name='relinitial',
            options={'ordering': ['parent_question']},
        ),
    ]
