# Generated by Django 3.2.6 on 2021-08-06 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_relative_parent_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relative',
            name='parent_initial',
        ),
        migrations.RemoveField(
            model_name='relative',
            name='parent_question',
        ),
        migrations.AddField(
            model_name='relinitial',
            name='cildrean_relative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.relative'),
        ),
    ]
