# Generated by Django 3.2.6 on 2021-08-06 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210806_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relinitial',
            name='cildrean_relative',
        ),
        migrations.AddField(
            model_name='relative',
            name='parent_initial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
