# Generated by Django 3.2.6 on 2021-08-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210806_0512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relative',
            options={'verbose_name': 'Буква', 'verbose_name_plural': 'Буквы'},
        ),
        migrations.AlterModelOptions(
            name='relinitial',
            options={'verbose_name': 'Число', 'verbose_name_plural': 'Числа'},
        ),
        migrations.AddField(
            model_name='question',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Разбор, комментарии'),
        ),
    ]
