# Generated by Django 3.2.6 on 2021-09-22 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('stage', models.CharField(max_length=100, verbose_name='Олимпиада')),
                ('grade', models.IntegerField(verbose_name='Класс')),
                ('part', models.IntegerField(verbose_name='Часть')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Вопрос загружен')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('type', models.CharField(choices=[('P1', '1 правильный ответ'), ('P2', 'Множественный выбор'), ('REL', 'Соответствие'), ('MANY', 'Пункты'), ('STR', 'Текст')], default='STR', max_length=4, verbose_name='Тип')),
                ('comment', models.TextField(blank=True, verbose_name='Разбор, комментарии')),
                ('coauthor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Добавил разбор')),
                ('quauthor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Добавил вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.CharField(max_length=1000, verbose_name='Текст варианта')),
                ('parent_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
            options={
                'verbose_name': 'Буква',
                'verbose_name_plural': 'Буквы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.CharField(max_length=1000, verbose_name='Текст варианта')),
                ('is_right', models.BooleanField(default=False, verbose_name='Правильность')),
                ('parent_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'ordering': ['parent_question'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='main.tag')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['parent_tag', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RelInitial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.CharField(max_length=1000, verbose_name='Текст варианта')),
                ('parrent_relative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.relative')),
            ],
            options={
                'verbose_name': 'Число',
                'verbose_name_plural': 'Числа',
            },
        ),
        migrations.CreateModel(
            name='QuStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quimage', models.ImageField(blank=True, upload_to='images/qu', verbose_name='Иллюстрация к вопросу')),
                ('coimage', models.ImageField(blank=True, upload_to='images/co', verbose_name='Иллюстрация к разбору')),
                ('cofile', models.FileField(blank=True, upload_to='files/', verbose_name='Прикрепленный файл')),
                ('label', models.CharField(blank=True, max_length=500, verbose_name='Подпись')),
                ('q', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['q'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='main.Tag'),
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='questions', to='main.Topic'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Вопрос')),
                ('ans', models.TextField(verbose_name='Ответ')),
                ('parent_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
            options={
                'verbose_name': 'Пункт',
                'verbose_name_plural': 'Пункты',
                'ordering': ['parent_question'],
            },
        ),
    ]
