# Generated by Django 3.2.6 on 2021-09-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_question_coauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='flag',
            field=models.CharField(choices=[('CORE', 'ВсОШ'), ('EXTRA', 'Другие олимпиады'), ('COM', 'От пользователей'), ('EXCL', 'Эксклюзив от создателей')], default='CORE', max_length=10, verbose_name='Тип'),
        ),
    ]
