# Generated by Django 3.2.6 on 2021-08-05 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210806_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='vars',
        ),
        migrations.AddField(
            model_name='varlist',
            name='parent_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
