# Generated by Django 3.2.6 on 2021-09-22 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0003_question_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Разбор, комментарии')),
                ('mark', models.BooleanField(default=False, verbose_name='Проверено экспертом')),
                ('coauthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Добавил разбор')),
            ],
            options={
                'verbose_name': 'Разбор',
                'verbose_name_plural': 'Разборы',
                'ordering': ['parent_question'],
            },
        ),
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, upload_to='images/', verbose_name='Иллюстрация')),
                ('label', models.CharField(blank=True, max_length=500, verbose_name='Подпись')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['parent_question'],
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='coauthor',
        ),
        migrations.RemoveField(
            model_name='question',
            name='comment',
        ),
        migrations.DeleteModel(
            name='QuStorage',
        ),
        migrations.AddField(
            model_name='multipleimage',
            name='parent_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
