# Generated by Django 3.2.6 on 2021-09-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210923_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multipleimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RemoveField(
            model_name='multipleimage',
            name='parent_question',
        ),
    ]
