# Generated by Django 3.2.6 on 2021-08-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210806_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('P1', '1 правильный ответ'), ('P2', 'Множественный выбор'), ('REL', 'Соответствие'), ('MANY', 'Пункты'), ('STR', 'Текст')], default='STR', max_length=4, verbose_name='Тип'),
        ),
    ]
