# Generated by Django 3.2.6 on 2021-09-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_comment_parent_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='text',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='flag',
            field=models.CharField(choices=[('CORE', 'ВсОШ'), ('EXTRA', 'Другие олимпиады'), ('COM', 'От пользователей'), ('EXCL', 'Эксклюзив от создателей')], default='CORE', max_length=10, verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='var',
            field=models.TextField(verbose_name='Текст варианта'),
        ),
        migrations.AlterField(
            model_name='relinitial',
            name='var',
            field=models.TextField(verbose_name='Текст варианта'),
        ),
        migrations.AlterField(
            model_name='varlist',
            name='var',
            field=models.TextField(verbose_name='Текст варианта'),
        ),
    ]
