# Generated by Django 3.2.6 on 2021-09-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210923_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='comment',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Вопрос загружен'),
        ),
    ]
