# Generated by Django 3.2.6 on 2021-08-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210806_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varlist',
            name='is_right',
            field=models.BooleanField(default=False, verbose_name='Правильность'),
        ),
    ]
