# Generated by Django 3.2.6 on 2021-08-06 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_varlist_is_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.CharField(max_length=200, verbose_name='Текст варианта')),
            ],
        ),
        migrations.AlterModelOptions(
            name='varlist',
            options={},
        ),
        migrations.AlterField(
            model_name='varlist',
            name='var',
            field=models.CharField(max_length=200, verbose_name='Текст варианта'),
        ),
        migrations.CreateModel(
            name='RelInitials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.CharField(max_length=200, verbose_name='Текст варианта')),
                ('parent_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question')),
                ('relatives', models.ManyToManyField(blank=True, related_name='ri', to='main.Relative')),
            ],
            options={
                'ordering': ['parent_question'],
            },
        ),
    ]
