# Generated by Django 3.2.6 on 2021-09-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_multiplefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplefile',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterField(
            model_name='multipleimage',
            name='file',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Прикрепленнное изображение'),
        ),
    ]
