# Generated by Django 3.2.6 on 2021-09-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210923_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='part',
            field=models.CharField(max_length=100, verbose_name='Часть'),
        ),
    ]
