# Generated by Django 3.2.6 on 2021-09-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_question_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='question',
            name='part',
            field=models.CharField(max_length=100, null=True, verbose_name='Часть'),
        ),
        migrations.AlterField(
            model_name='question',
            name='stage',
            field=models.CharField(max_length=100, null=True, verbose_name='Олимпиада'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст вопроса'),
        ),
    ]
