# Generated by Django 3.2.6 on 2021-08-06 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210806_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relinitial',
            name='relatives',
        ),
        migrations.AddField(
            model_name='relative',
            name='parent_initial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.relinitial'),
        ),
    ]
