# Generated by Django 3.2.6 on 2021-09-26 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210926_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.comment'),
        ),
        migrations.AddField(
            model_name='coimage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.comment'),
        ),
        migrations.AddField(
            model_name='quimage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.question'),
        ),
    ]
