# Generated by Django 3.2.6 on 2021-08-06 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210806_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='relative',
            name='parent_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
