# Generated by Django 3.2.6 on 2021-09-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210926_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cofile',
            options={'verbose_name': 'Файл к разбору', 'verbose_name_plural': 'Файлы к разбору'},
        ),
        migrations.AlterModelOptions(
            name='coimage',
            options={'verbose_name': 'Иллюстрация к рабору', 'verbose_name_plural': 'Иллюстрации к разбору'},
        ),
    ]
