# Generated by Django 3.2.6 on 2021-10-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210926_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coimage',
            old_name='file',
            new_name='coifile',
        ),
        migrations.RenameField(
            model_name='coimage',
            old_name='label',
            new_name='coilabel',
        ),
        migrations.RenameField(
            model_name='coimage',
            old_name='parent',
            new_name='coiparent',
        ),
        migrations.RenameField(
            model_name='quimage',
            old_name='file',
            new_name='quifile',
        ),
        migrations.RenameField(
            model_name='quimage',
            old_name='label',
            new_name='quilabel',
        ),
        migrations.RenameField(
            model_name='quimage',
            old_name='parent',
            new_name='quiparent',
        ),
    ]
