# Generated by Django 3.2.6 on 2021-08-06 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210806_0503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relinitial',
            options={'ordering': ['var']},
        ),
        migrations.RemoveField(
            model_name='relative',
            name='parent_initial',
        ),
        migrations.RemoveField(
            model_name='relinitial',
            name='parent_question',
        ),
        migrations.AddField(
            model_name='relative',
            name='parent_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
        migrations.AddField(
            model_name='relinitial',
            name='parrent_relative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.relative'),
        ),
    ]
