# Generated by Django 3.2.6 on 2021-10-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20211018_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlist',
            old_name='ans',
            new_name='itemans',
        ),
        migrations.RenameField(
            model_name='itemlist',
            old_name='text',
            new_name='itemtext',
        ),
        migrations.RenameField(
            model_name='relative',
            old_name='var',
            new_name='lettervar',
        ),
        migrations.RenameField(
            model_name='relinitial',
            old_name='var',
            new_name='numbervar',
        ),
    ]
