# Generated by Django 3.2.6 on 2021-08-07 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210806_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='topics',
        ),
        migrations.AddField(
            model_name='topic',
            name='parent_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ts', to='main.tag'),
        ),
    ]
