# Generated by Django 3.2.6 on 2021-08-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210807_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['parent_tag', 'name'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
