# Generated by Django 3.2.6 on 2021-08-26 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_topic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Иллюстрация к вопросу'),
        ),
        migrations.AddField(
            model_name='question',
            name='image5',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Иллюстрация к вопросу'),
        ),
        migrations.AddField(
            model_name='question',
            name='imageA4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Иллюстрация к вопросу'),
        ),
        migrations.AddField(
            model_name='question',
            name='imageA5',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Иллюстрация к вопросу'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='var',
            field=models.CharField(max_length=1000, verbose_name='Текст варианта'),
        ),
        migrations.AlterField(
            model_name='relinitial',
            name='var',
            field=models.CharField(max_length=1000, verbose_name='Текст варианта'),
        ),
        migrations.AlterField(
            model_name='varlist',
            name='var',
            field=models.CharField(max_length=1000, verbose_name='Текст варианта'),
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Вопрос')),
                ('ans', models.TextField(verbose_name='Ответ')),
                ('parent_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
            options={
                'verbose_name': 'Пункт',
                'verbose_name_plural': 'Пункты',
                'ordering': ['parent_question'],
            },
        ),
    ]
